name: Matrix Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        dot-net-version: [7.0.x]
        include:
          - os: ubuntu-latest
            dot-net-version: 2.1.x

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dot-net-version }}
 
    - name: Restore dependecies
      run: dotnet restore
